---
# handlers file for demo-app

- name: Restart chrony service
  service:
    name: chronyd
    state: restarted

- name: Restart sshd service
  service:
    name: sshd
    state: restarted
  when: ansible_distribution == "CentOS"

- name: Restart ssh service
  service:
    name: ssh
    state: restarted
  when: ansible_distribution == "Ubuntu"
