---

- name: Setup DB
  hosts: dbservergrp
  become: true
  tasks:
    - name: Install mysql server 
      apt:
        name: mysql-server
        state: present

    - name: Start and enable mysql server
      service:
        name: mysql
        state: started
        enabled: yes
        
