---
- name: Setup Webserver
  hosts: web
  become: True
  tasks:
   - name: Install Apache2 package
     apt:
       name: apache2
       state: present
       #state: absent [Removed the Service]


   - name: Start Apache2 Service
     service:
       name: apache2
       state: started
       enabled: yes

   - name: Copy Model
     copy:
       src: index.html
       dest: /var/www/html/

- name: Mysql Server Setup
  hosts: dbservergrp
  become: True
  tasks:
   - name: Install Mysql Server
     apt:
      name: mysql-server
      state: present

   - name: Start and enabel mysql-server
     service:
      name: mysql-server
      state: present
      enabled: yes
