---

- name: Conditions Practice
  hosts: all
  become: true
  tasks:
    - name: Install pkg
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"


    - name: Install pkg
      yum:
        name: mariadb-server
        state: present
      when: ansible_distribution == "CentOS"
